In [1]:
import numpy as np
import pandas as pd


In [2]:
data = pd.read_csv('data.csv')

In [ ]:
data

In [3]:
print(type(data))

<class 'pandas.core.frame.DataFrame'>


In [4]:
data = data.fillna(value=0)

In [ ]:
data

In [5]:
x = data.drop(['suprise_r1', 'suprise_r2', 'suprise_r3'], axis = 1)

In [ ]:
x 

In [6]:
x_new =  x.drop(['avg_surprise'], axis = 1)

In [ ]:
x_new

In [7]:
x_new = x_new.drop(['link', 'title'], axis = 1)

In [ ]:
x_new

In [8]:
x_new['main_category']= pd.get_dummies(x_new['main_category'])

In [9]:
x_new['category_1']= pd.get_dummies(x_new['category_1'])

In [10]:
x_new['category_2']= pd.get_dummies(x_new['category_2'])

In [11]:
x_new['category_3']= pd.get_dummies(x_new['category_3'])

In [12]:
x_new['category_4']= pd.get_dummies(x_new['category_4'])

In [ ]:
x_new

In [13]:
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer

In [ ]:
tf = TfidfVectorizer(stop_words = 'english', ngram_range = (1,3))

In [14]:
cv = CountVectorizer(stop_words = 'english', ngram_range=(1,3))

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
y = x.iloc[:, -1]

In [ ]:
print(type(y))

In [17]:
y = pd.DataFrame(y)

In [18]:
y

avg_surprise
0        2.333333
1        4.666667
2        3.666667
3        1.000000
4        2.333333
5        2.333333
6        4.333333
7        1.333333
8        2.333333
9        1.666667
10       3.666667
11       2.000000
12       4.000000
13       3.666667
14       4.000000
15       2.666667
16       2.000000
17       3.000000
18       2.333333
19       2.666667
20       3.000000
21       1.333333
22       3.333333
23       3.000000
24       3.000000
25       4.000000
26       4.333333
27       4.333333
28       3.000000
29       3.666667
..            ...
470      4.000000
471      4.000000
472      2.333333
473      3.666667
474      1.666667
475      3.000000
476      2.666667
477      2.666667
478      3.000000
479      4.333333
480      3.666667
481      2.666667
482      3.000000
483      3.666667
484      2.333333
485      2.333333
486      2.333333
487      1.666667
488      2.666667
489      3.666667
490      4.333333
491      3.000000
492      3.000000
493      3.333333
494      3.333333
495      2.666667
496      1.333333
497      3.666667
498      3.000000
499      3.666667

[500 rows x 1 columns]

In [21]:
Y = y < 3

In [22]:
Y = Y.astype(int)

In [23]:
Y

avg_surprise
0               1
1               0
2               0
3               1
4               1
5               1
6               0
7               1
8               1
9               1
10              0
11              1
12              0
13              0
14              0
15              1
16              1
17              0
18              1
19              1
20              0
21              1
22              0
23              0
24              0
25              0
26              0
27              0
28              0
29              0
..            ...
470             0
471             0
472             1
473             0
474             1
475             0
476             1
477             1
478             0
479             0
480             0
481             1
482             0
483             0
484             1
485             1
486             1
487             1
488             1
489             0
490             0
491             0
492             0
493             0
494             0
495             1
496             1
497             0
498             0
499             0

[500 rows x 1 columns]

In [24]:
X_train, X_test, y_train, y_test = train_test_split(x_new, Y, test_size = 0.10)

In [25]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)


(450, 23)
(50, 23)
(450, 1)
(50, 1)


In [ ]:
print(type(X_train))

In [26]:
X_train['article'] = cv.fit_transform(X_train['article'])

C:\Users\Ketki\Anaconda_new\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [27]:
X_test['article'] = cv.transform(X_test['article'])

C:\Users\Ketki\Anaconda_new\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [28]:
from sklearn.linear_model import LogisticRegression

In [29]:
lr = LogisticRegression()

In [ ]:
#X = X_train.iloc[:,-1]

In [33]:
X = X_train.drop(['article'], axis = 1)

In [30]:
print(type(X_train))

<class 'pandas.core.frame.DataFrame'>


In [34]:
X_t = X_test.drop(['article'], axis = 1)

In [35]:
lr.fit(X,y_train)

C:\Users\Ketki\Anaconda_new\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [41]:
lr_pred = lr.predict(X_t)

In [42]:
from sklearn import metrics

print((metrics.classification_report(lr_pred, y_test)))

             precision    recall  f1-score   support

          0       0.97      0.60      0.74        48
          1       0.05      0.50      0.09         2

avg / total       0.93      0.60      0.72        50



In [43]:
print(metrics.confusion_matrix(y_test, lr_pred))

[[29  1]
 [19  1]]


In [44]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier

C:\Users\Ketki\Anaconda_new\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


In [45]:
rf = RandomForestClassifier()

In [46]:
rf.fit(X,y_train)

C:\Users\Ketki\Anaconda_new\lib\site-packages\ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """Entry point for launching an IPython kernel.


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [47]:
rf_pred = rf.predict(X_t)

In [48]:
print((metrics.classification_report(rf_pred, y_test)))

             precision    recall  f1-score   support

          0       0.70      0.62      0.66        34
          1       0.35      0.44      0.39        16

avg / total       0.59      0.56      0.57        50



In [49]:
print(metrics.confusion_matrix(y_test, rf_pred))

[[21  9]
 [13  7]]


In [50]:
from xgboost import XGBClassifier

In [51]:
classifier = XGBClassifier()

In [52]:
classifier.fit(X,y_train)

C:\Users\Ketki\Anaconda_new\lib\site-packages\sklearn\preprocessing\label.py:95: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Ketki\Anaconda_new\lib\site-packages\sklearn\preprocessing\label.py:128: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, learning_rate=0.1, max_delta_step=0,
       max_depth=3, min_child_weight=1, missing=None, n_estimators=100,
       n_jobs=1, nthread=None, objective='binary:logistic', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
       silent=True, subsample=1)

In [53]:
xg_pred = classifier.predict(X_t)

C:\Users\Ketki\Anaconda_new\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


In [54]:
print((metrics.classification_report(xg_pred, y_test)))

             precision    recall  f1-score   support

          0       0.63      0.73      0.68        26
          1       0.65      0.54      0.59        24

avg / total       0.64      0.64      0.64        50



In [55]:
print(metrics.confusion_matrix(y_test, xg_pred))

[[19 11]
 [ 7 13]]
